(ns psi.ai.providers.openai.common
  (:require [psi.ai.providers.openai.content :as content]
            [psi.ai.providers.openai.reasoning :as reasoning]
            [psi.ai.providers.openai.transport :as transport]))

(def thinking-level->effort reasoning/thinking-level->effort)
(def reasoning-part-types reasoning/reasoning-part-types)
(def reasoning-effort reasoning/reasoning-effort)

(def normalize-part-type content/normalize-part-type)
(def join-parts content/join-parts)
(def string-fragment content/string-fragment)
(def normalize-tool-arguments content/normalize-tool-arguments)
(def accumulate-tool-arguments content/accumulate-tool-arguments)
(def content-text content/content-text)
(def structured-blocks content/structured-blocks)
(def text-blocks content/text-blocks)
(def tool-call-blocks content/tool-call-blocks)
(def block-text content/block-text)
(def join-block-text content/join-block-text)
(def structured-text content/structured-text)
(def assistant-structured-content content/assistant-structured-content)
(def user-message-text content/user-message-text)
(def new-msg-id content/new-msg-id)
(def new-call-id content/new-call-id)
(def tool-result-text content/tool-result-text)
(def chat-tool-call content/chat-tool-call)
(def codex-tool-call-ids content/codex-tool-call-ids)
(def codex-tool-call-item content/codex-tool-call-item)
(def codex-message-item content/codex-message-item)
(def pad-base64url content/pad-base64url)
(def extract-chatgpt-account-id content/extract-chatgpt-account-id)

(def safe-call! transport/safe-call!)
(def stream-response transport/stream-response)
(def redact-authorization transport/redact-authorization)
(def mask-chatgpt-account-id transport/mask-chatgpt-account-id)
(def redact-request-headers transport/redact-request-headers)
(def parse-json-body-safe transport/parse-json-body-safe)
(def capture-request! transport/capture-request!)
(def capture-response! transport/capture-response!)
(def parse-sse-line transport/parse-sse-line)
(def body->text transport/body->text)
(def parse-json-text-safe transport/parse-json-text-safe)
(def parsed-error-message transport/parsed-error-message)
(def parse-error-message transport/parse-error-message)
(def request-id-from-headers transport/request-id-from-headers)
(def meaningful-error-message? transport/meaningful-error-message?)
(def fallback-status-message transport/fallback-status-message)
(def base-error-message transport/base-error-message)
(def error-message transport/error-message)
(def error-from-response-data transport/error-from-response-data)
(def error-status? transport/error-status?)
(def response->error transport/response->error)
(def emit-error! transport/emit-error!)
(def exception->error transport/exception->error)

(def default-codex-base-url "https://chatgpt.com/backend-api")
(def codex-beta-header "responses=experimental")
